library(sqldf); library(dplyr); library(ggplot2); library(jpeg)
df <- read.csv.sql("C:/Users/gsand/OneDrive/Desktop/Online Training/JH/Mod4/Lec1/exdata_data_household_power_consumption/household_power_consumption.txt", "select * from file where Date in ('1/2/2007',  '2/2/2007') ", sep=";")
summary(df)
df$Date <- strptime(df$Date, format = '%d/%m/%Y')
df$Time <- format(strptime(df$Time, "%H:%M:%S"),"%H:%M:%S")
write.csv(df,'df.csv',)
png("plot1.png", width = 480, height = 480)
hist(df$Global_active_power, col = 'red', main = 'Global Active Power', xlab = 'Global Active Power (in kilowatt)', xlim = )
dev.off()